# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.3

    working_directory: ~/geo_tools

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
            sudo apt-get update
            sudo apt-get update && sudo apt-get install -y gdal-bin python-gdal python3-gdal libgdal-dev
            export CPLUS_INCLUDE_PATH=/usr/include/gdal
            export C_INCLUDE_PATH=/usr/include/gdal
            python3 -m venv geo_tools_env
            source geo_tools_env/bin/activate
            pip install -r requirements.txt

      # run tests!
      - run:
          name: run tests
          command: |
            source geo_tools_env/bin/activate
            python3 -m pytest tests

      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-reports
          destination: test-reports