# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
      - image: circleci/postgres:9.6.12-postgis

    working_directory: ~/geo_tools

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            conda config --set quiet true
            conda create -y --name geo_tools python==3.6
            conda install -y -q --name geo_tools -c conda-forge --file requirements.txt

      # run tests!
      - run:
          name: run tests
          command: |
            activate geo_tools
            python -m pytest tests

      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-reports
          destination: test-reports