# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
      - image: circleci/postgres:9.6.12-postgis

    working_directory: ~/geo_tools

    steps:
      - checkout

      - restore_cache:
          keys:
            - geo_tools_cache

      - run:
          name: install dependencies
          command: |
            conda config --set quiet true
            conda create -y --name geo_tools python==3.6
            conda config --add channels conda-forge
            conda install -y -q --name geo_tools -c conda-forge --file requirements.txt

      - save_cache:
          key: geo_tools_cache
          paths:
            - "/opt/conda/envs/geo_tools"

      - run:
          name: run tests
          command: |
            source activate geo_tools
            python3 -m pytest tests

      - store_test_results:
          path: .gitignore-results
      - store_artifacts:
          path: .gitignore-reports
          destination: .gitignore-reports

    steps:
