# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: continuumio/anaconda3

    working_directory: ~/geo_tools

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            conda config --add channels conda-forge
            conda config --set channel_priority strict
            conda install --file requirements.txt

      # run tests!
      - run:
          name: run tests
          command: |
            python -m pytest tests

      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-reports
          destination: test-reports