# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
      - image: circleci/postgres:9.6.12-postgis

    working_directory: ~/geo_tools

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            conda config --add channels conda-forge
            conda config --set always_yes true
            conda config --set quiet true
            conda env create -n geo_tools python=3.6
            activate geo_tools
            conda install --file requirements.txt

      # run tests!
      - run:
          name: run tests
          command: |
            activate geo_tools
            python -m pytest tests

      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-reports
          destination: test-reports