name: Python 3.6 - tests

on:
  push:
    branches:
    - master
    - dev

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v1
    - name: Install Postgres/GIS
      run: |
        sudo apt install postgresql-10 --yes
        sudo apt install postgresql-10-postgis-2.4 --yes
    - name: Install Miniconda3
      run: |
        # sudo apt update --yes
        # sudo apt upgrade --yes
        wget https://repo.continuum.io/miniconda/Miniconda3-4.7.10-Linux-x86_64.sh -O ~/miniconda.sh
        bash ~/miniconda.sh -b -p ~/miniconda 
        rm ~/miniconda.sh
    - name: Prepare conda env
      run: |
        conda config --set quiet true
        conda create -y --name geo_tools python=3.6
        conda config --add channels conda-forge
        conda install -y -q --name geo_tools -c conda-forge --file requirements.txt
    - name: Test with pytest
      run: |
        activate geo_tools
        python3 -m pytest tests
